### ISSUE TITLE
No test artifacts built

### ISSUE THREAD

**Issue by obraunsdorf** [danielzfranklin/cargo-rr#1]
Hi, 
thanks for the rr-wrapper! This is very convenient :)
Unfortunately I get an error when trying to run a test: `Error: cargo-rr: No test artifacts built.`

Steps to reproduce:
```
cargo new --lib bla
cd bla
cargo rr test it_works
```

**Comment by dzfranklin** [comment]
Thanks! Fixed in the latest version published.
