### ISSUE TITLE
Add install instructions to readme

### ISSUE THREAD

**Issue by dzfranklin** [danielzfranklin/cargo-rr#3]

**Comment by grunweg** [comment]
Hi! Thanks a lot for creating your project, it looks really promising. I've been following the `rr` project for a long time but was always slightly intimidated by having to live in the terminal. Your project lowers the bar for trying `rr`, so I could actually use it!

Sadly, I can't seem to install your package correctly --- some instructions would help. I tried this.
1. Add `cargo-rr` to my Cargo.toml file. (In my case, running `cargo add cargo-rr`.)
2. Then, `cargo rr cargo test` (or even `cargo rr`) both yield the same error: no such subcommand: `rr`.

I presume the correct incantation won't be hard, but I'm at a loss at finding it. Even brief instructions would be helpful. Thanks a lot.

PS. I did try just using stock `rr`, e.g. by running `rr record cargo test && rr replay`. However, something is wrong: my replay doesn't see the source of my program ("No source file named src/file.rs"), and I suspect your tool may allow me to overcome this.

**Comment by dzfranklin** [comment]
Hi grunweg,

cargo-rr is something you install system-wide, not to a specific project. The incantation you want is `cargo install cargo-rr`. Please don't hesitate to reach out if you run into further issues.

**Comment by grunweg** [comment]
I could've sworn I tried doing this before --- upon which it didn't work, so I tried adding it to my Cargo.toml.
I just tried it again and now it works... funny. Thanks for the quick response!

**Comment by grunweg** [comment]
@danielzfranklin I took a stab at writing some installation instructions: #7

**Comment by grunweg** [comment]
I guess this can be closed now. :smiley:
